# Generated by Django 2.1.15 on 2020-07-29 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_marketing',
            new_name='is_staff',
        ),
    ]
