version: "3.7"

services:
    backend: 
        build: ./backend
        image: "backend"
        ports: 
            - "8000:8000"
        networks:
            - "appnetwork"
        
        volumes:
            - ./backend:/backend
        
        stdin_open: true
        tty: true
        
        depends_on: 
            - "pgdb"
        
        command: >
            sh -c "python manage.py wait_for_db && 
                    python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000"
    
        env_file: .env

    pgdb:
        image: "postgres:10-alpine"
        restart: always
        networks:
            - "appnetwork"

        env_file: .env-db
    
networks:
    appnetwork:
        driver: bridge