version: "3.7"

services:
    backend: 
        build: ./backend
        image: "backend"
        ports: 
            - "8000:8000"
        networks:
            - "appnetwork"
        
        volumes:
            - ./backend:/backend
        
        stdin_open: true
        tty: true
        
        depends_on: 
            - "pgdb"
        
        command: >
            sh -c "python manage.py wait_for_db && 
                    python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000"
    
        environment:
            - DB_HOST=pgdb
            - DB_NAME=lead_app
            - DB_USER=dbuser
            - DB_PASS=dbpassword

    pgdb:
        image: "postgres:10-alpine"

        networks:
            - "appnetwork"

        environment:
            - POSTGRES_USER=dbuser
            - POSTGRES_PASSWORD=dbpassword
            - POSTGRES_DB=lead_app

    frontend:
        build: ./frontend

        image: "frontend"

        ports:
            - "3000:3000"

        networks:
            - "appnetwork"

        volumes:
            - ./frontend:/frontend
            - /frontend/node_modules
        
        stdin_open: true
        tty: true
        
        environment: 
            - NODE_ENV=development

        depends_on:
            - backend

        command: >
            sh -c "npm start"
    
networks:
    appnetwork:
        driver: bridge